### ISSUE TITLE
Migrate to cloud-gov GitHub org

### ISSUE THREAD

**Issue by amirbey** [cloud-gov/federalist#3423]
#### Background (Optional)

Migrate federalist repos to cloud-gov GitHub organization.

#### Acceptance Criteria
- [ ] [Migrate Project Board](https://github.com/orgs/cloud-gov/projects/23)
- [x] Migrate federalist.18f.gov repo
- [x] Migrate federalist repo
- [x] Migrate federalist-builder repo
- [x] Migrate federalist-garden-build repo
- [x] Migrate proxy-server repo
- [x] Migrate federalist-404-page
- [x] Migrate the federalist templates
  - [x] jekyll
  - [x] gatsby
- [x] Update concourse pipelines 

_After evaluating, edit this part:_

#### Implementation outline (if higher than "low" effort):

- [x] discuss organization/repo permissions with cloud-gov GitHub org admin
- [x] obtain permission for Pages team in cloud-gov ... possibly a Pages GitHub team
- [x] coordinate with 18F org GitHub admin to transfer repositories to cloud-gov
- [x] coordinate with cloud-gov org GitHub admin to transfer repositories to cloud-gov

Considerations: CircleCI, CodeClimate, Concourse, ...?

Related to epic: https://github.com/orgs/cloud-gov/projects/25

**Comment by drewbo** [comment]
https://github.com/cloud-gov/product/issues/2118 will track the remaining issue transfer, all repos are moved
